{
 "title": "Kubernetes Nodes",
 "description": "Dashboard to for node information",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(kube_pod_info, host_ip)"
   },
   {
    "name": "instance",
    "query": "label_values(kube_pod_info{host_ip=~\"$server\"}, node)"
   },
   {
    "name": "pods",
    "query": "label_values(container_cpu_usage_seconds_total{kubernetes_io_hostname =~\"$instance\"}, pod_name)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "1 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$server:.*\"}[5m])))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$server:.*\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "avg(node_load5{instance=~\"$server:.*\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "avg(node_load15{instance=~\"$server:.*\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$server:.*\"} - node_memory_MemFree_bytes{instance=~\"$server:.*\"} - node_memory_Buffers_bytes{instance=~\"$server:.*\"} - node_memory_Cached_bytes{instance=~\"$server:.*\"})",
     "legendFormat": "memory used"
    },
    {
     "expr": "avg(node_memory_Buffers_bytes{instance=~\"$server:.*\"})",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "avg(node_memory_Cached_bytes{instance=~\"$server:.*\"})",
     "legendFormat": "memory cached"
    },
    {
     "expr": "avg(node_memory_MemFree_bytes{instance=~\"$server:.*\"})",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "description": "-/+ buffers/cache",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes{instance=~\"$server:.*\"} - node_memory_MemFree_bytes{instance=~\"$server:.*\"}  - node_memory_Buffers_bytes{instance=~\"$server:.*\"} - node_memory_Cached_bytes{instance=~\"$server:.*\"}) / node_memory_MemTotal_bytes{instance=~\"$server:.*\"})"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{instance=~\"$server:.*\"}[2m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$server:.*\"}[2m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{instance=~\"$server:.*\"}[2m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=~\"$server:.*\"}) - sum(node_filesystem_free_bytes{device!=\"rootfs\",instance=~\"$server:.*\"})) / sum(node_filesystem_size_bytes{device!=\"rootfs\",instance=~\"$server:.*\"})"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(device) (rate(node_network_receive_bytes_total{instance=~\"$server:.*\",device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "sum (rate(node_network_receive_bytes_total{instance=~\"$server:.*\",device!~\"lo\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(device) (rate(node_network_transmit_bytes_total{instance=~\"$server:.*\",device!~\"lo\"}[5m]))",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "sum (rate(node_network_transmit_bytes_total{instance=~\"$server:.*\",device!~\"lo\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Pods on Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\", node=~\"$instance\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (container_memory_usage_bytes{node=\"$instance\", container_name!=\"POD\",container_name!=\"\", pod_name!=\"\"})",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}